### ISSUE TITLE
Should it works with dash symbol in name?

### ISSUE THREAD

**Issue by SanichKotikov** [css-modules/postcss-modules-values#27]
Hi,

For example, I have next code:

```css
/* values.css */
@value test-t: 40px;
@value test_q: 36px;
```

```css
@value test-t, test_q from "values.css";

.root {
  height: test-t;
  height: test_q;
}
```

Result I've got:

```css
.Comp__root__wrlsR {
  height: undefined;
  height: 36px;
}
```

Webpack rule I use:

```js
{
    test: /\.css$/,
    exclude: /node_modules/,
    sideEffects: true,
    use: [
        isProd ? MiniCssExtractPlugin.loader : 'style-loader',
        {
            loader: 'css-loader',
            options: {
                importLoaders: 1,
                modules: {
                    mode: 'local',
                    exportLocalsConvention: 'dashesOnly',
                    localIdentName: isProd ? '[hash:base64:5]' : '[name]__[local]__[hash:base64:5]',
                },
            },
        },
        {
            loader: 'postcss-loader',
            options: {
                postcssOptions: {
                    plugins: {
                        'postcss-nesting': {},
                        'postcss-modules-values': {},
                        ...(isProd && { autoprefixer: { flexbox: 'no-2009' } }),
                    },
                },
            },
        },
    ],
},
```

Is there something I've missed?
