### ISSUE TITLE
A PostCSS plugin did not pass the `from` option to `postcss.parse`.

### ISSUE THREAD

**Issue by kkkisme** [css-modules/postcss-modules-values#40]
when use postcss@8.4.23 and this plugin , will show below warning message:
```
A PostCSS plugin did not pass the `from` option to `postcss.parse`. This may cause imported assets to be incorrectly transformed. If you've recently added a PostCSS plugin that raised this warning, please contact the package author to fix the issue.
```

**Comment by kevinkace** [comment]
I'm using `postcss-modules-values` with SvelteKit, and seeing this error as well as values not importing correctly from other files.

```css
/* global.css */
@value testColor: red;
```

```css
/* +layout.svelte */
@value testColor from "../global.css";
.header {
    background-color: testColor;
}
```
![image](https://github.com/css-modules/postcss-modules-values/assets/532448/c58837c0-58a7-4e92-aac7-a233a65e840a)
